# Generated by Django 4.1.3 on 2022-11-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia',
            name='name',
        ),
        migrations.AddField(
            model_name='dia',
            name='estado',
            field=models.CharField(choices=[('Passado', 'Passado'), ('Perdido', 'Perdido'), ('Neutro', 'Neutro')], default='Neutro', max_length=7),
        ),
    ]
