# Generated by Django 4.1.3 on 2022-11-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_app', '0002_remove_dia_name_dia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='estado',
            field=models.CharField(choices=[(1, 'Neutro'), (2, 'Passado'), (3, 'Perdido')], default='Neutro', max_length=7),
        ),
    ]
