# Generated by Django 4.1.3 on 2022-11-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_app', '0003_alter_dia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='estado',
            field=models.CharField(choices=[('Neutro', 'Neutro'), ('Passado', 'Passado'), ('Perdido', 'Perdido')], default='Neutro', max_length=7),
        ),
    ]
