# Generated by Django 4.1.3 on 2022-11-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_app', '0005_alter_dia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='estado',
            field=models.CharField(choices=[(1, 'Neutro'), (2, 'Passado'), (3, 'Perdido')], default=(1, 'Neutro'), max_length=7),
        ),
    ]
