# Generated by Django 4.1.3 on 2022-11-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core_app', '0010_alter_dia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dia',
            name='dia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setembro',
            name='dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core_app.dia'),
        ),
    ]
