# Generated by Django 4.1.3 on 2022-11-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core_app', '0011_dia_dia_alter_setembro_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setembro',
            name='dia',
        ),
        migrations.AddField(
            model_name='dia',
            name='mes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='Core_app.setembro'),
        ),
    ]
