# Generated by Django 4.1.3 on 2022-11-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_app', '0012_remove_setembro_dia_dia_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='estado',
            field=models.CharField(choices=[('N', 'Neutro'), ('P', 'Passado'), ('F', 'Perdido')], default=('N', 'Neutro'), max_length=7),
        ),
    ]
