# Generated by Django 4.1.3 on 2022-11-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_app', '0013_alter_dia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SETEMBRO_GERAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHEGOU_SETEMBRO', models.BooleanField(default=False)),
            ],
        ),
    ]
